Make CMD Using SIMBAD Catalog

In [2]:
import pandas as pd
import numpy as np
from astropy.io import fits
from astropy.coordinates import SkyCoord
from astropy.wcs import WCS

In [3]:
pd.set_option('display.max_columns', None)  # or 1000
pd.set_option('display.max_rows', None)  # or 1000
pd.set_option('display.max_colwidth', None)  # or 199

In [26]:
cd /Users/ibehbehani/variablesearch/

/Users/ibehbehani/variablesearch

In [30]:
catalog = pd.read_csv("simbad_catalog_47_otype.txt",delimiter ="|",skipinitialspace=True,
                      names= ["Main_ID","OTYPE","RA","DEC","DIST"]) # read in simbad catalog

In [31]:
catalog.head(5)

,Main_ID,OTYPE,RA,DEC,DIST
0,main_id,otype,ra,dec,dist
1,---------------------------------,-----,------------------,------------------,---------------------
2,[MA2000] 3,Rad,5.9199166666666665,-72.08658333333334,0.031920713498508405
3,2MASS J00234168-7205028,RG*,5.92378068091,-72.0841029279,0.03043405401951269
4,2MASS J00234315-7205538,*,5.929797,-72.09829699999999,0.03307187366028807

In [32]:
#drop first few rows
catalog = catalog.drop([0,1,2],axis=0)

In [33]:
catalog.columns

Index(['Main_ID', 'OTYPE', 'RA', 'DEC', 'DIST'], dtype='object')

In [34]:
#reset index to start at zero
catalog = catalog.reset_index()
catalog = catalog.drop('index',axis=1)

In [35]:
# convert RA, DEC and DIST to floats
catalog['RA'] = catalog['RA'].astype(float)
catalog['DEC'] = catalog['DEC'].astype(float)
catalog['DIST'] = catalog['DIST'].astype(float)

In [36]:
catalog.head(5)

                           Main_ID OTYPE        RA        DEC      DIST
0  2MASS J00234168-7205028           RG*  5.923781 -72.084103  0.030434
1  2MASS J00234315-7205538           *    5.929797 -72.098297  0.033072
2  Cl* NGC  104    TUC    1331       *    5.928917 -72.086294  0.029142
3  2MASS J00233953-7204599           AB*  5.914807 -72.083293  0.033131
4  SWIFT J002405.8-720455            ev   6.024250 -72.082000  0.000811

Convert to wcs of each

In [37]:
catalog['RA'][0]

np.float64(5.92378068091)

In [38]:
cd /Users/ibehbehani/

/Users/ibehbehani

In [39]:
# open image data
fits_475 = fits.open('MAST_CMD/J6LL01010_475/j6ll01010_drz.fits')
fits_550 = fits.open('MAST_CMD/J6LL01YGQ_555/j6ll01ygq_drz.fits')

In [40]:
# get wcs data of each
w_475 = WCS(fits_475[1].header)
w_550 = WCS(fits_550[1].header)

In [41]:
print(catalog['RA'][0],catalog['DEC'][0])

5.92378068091 -72.0841029279

In [42]:
coord = SkyCoord(catalog['RA'][0],catalog['DEC'][0], unit = "deg")
coord

<SkyCoord (ICRS): (ra, dec) in deg
    (5.92378068, -72.08410293)>

In [43]:
a = w_475.world_to_pixel(coord)
print(a[0])

2636.6207688494187

In [44]:
catalog.shape[0]

829

In [45]:
#make empty ra and dec to fill
x_475 = np.zeros_like(catalog['RA'])
y_475 = np.zeros_like(catalog['DEC'])

for i in range(catalog.shape[0]):
    x_475[i],y_475[i] = w_475.world_to_pixel(SkyCoord(catalog['RA'][i],catalog['DEC'][i], unit = "deg"))

catalog['X_475'] = x_475
catalog['Y_475'] = y_475

In [46]:
catalog.head(10)

,Main_ID,OTYPE,RA,DEC,DIST,X_475,Y_475
0,2MASS J00234168-7205028,RG*,5.923781,-72.084103,0.030434,2636.620769,4452.136240
1,2MASS J00234315-7205538,*,5.929797,-72.098297,0.033072,3624.951077,4159.945055
2,Cl* NGC 104 TUC 1331,*,5.928917,-72.086294,0.029142,2774.567176,4314.997706
3,2MASS J00233953-7204599,AB*,5.914807,-72.083293,0.033131,2610.273638,4657.596751
4,SWIFT J002405.8-720455,ev,6.024250,-72.082000,0.000811,2138.987139,2277.821368
5,CXOGlb J002421.4-720433,X,6.089321,-72.075878,0.021352,1479.981129,921.971938
6,GES J00241041-7205445,*,6.043538,-72.095715,0.015691,3048.113043,1702.421343
7,PSR J0024-7204R,Psr,6.023625,-72.081283,0.000430,2090.169802,2299.526324
8,[CPF2015] COM-47TucW,WD?,6.025263,-72.080315,0.001446,2015.635127,2274.543905
9,Cl* NGC 104 LW 18,LP?,6.085561,-72.080463,0.019479,1819.056403,953.245682

In [47]:
#make empty ra and dec to fill
x_550 = np.zeros_like(catalog['RA'])
y_550 = np.zeros_like(catalog['DEC'])

for i in range(catalog.shape[0]):
    x_550[i],y_550[i] = w_550.world_to_pixel(SkyCoord(catalog['RA'][i],catalog['DEC'][i], unit = "deg"))

catalog['X_550'] = x_550
catalog['Y_550'] = y_550

In [48]:
catalog.head(15)

,Main_ID,OTYPE,RA,DEC,DIST,X_475,Y_475,X_550,Y_550
0,2MASS J00234168-7205028,RG*,5.923781,-72.084103,0.030434,2636.620769,4452.136240,2626.594268,4432.266319
1,2MASS J00234315-7205538,*,5.929797,-72.098297,0.033072,3624.951077,4159.945055,3614.925910,4140.079649
2,Cl* NGC 104 TUC 1331,*,5.928917,-72.086294,0.029142,2774.567176,4314.997706,2764.541302,4295.128416
3,2MASS J00233953-7204599,AB*,5.914807,-72.083293,0.033131,2610.273638,4657.596751,2600.246198,4637.726710
4,SWIFT J002405.8-720455,ev,6.024250,-72.082000,0.000811,2138.987139,2277.821368,2128.970569,2257.949176
5,CXOGlb J002421.4-720433,X,6.089321,-72.075878,0.021352,1479.981129,921.971938,1469.970751,902.096736
6,GES J00241041-7205445,*,6.043538,-72.095715,0.015691,3048.113043,1702.421343,3038.099101,1682.553304
7,PSR J0024-7204R,Psr,6.023625,-72.081283,0.000430,2090.169802,2299.526324,2080.153132,2279.653910
8,[CPF2015] COM-47TucW,WD?,6.025263,-72.080315,0.001446,2015.635127,2274.543905,2005.618572,2254.671150
9,Cl* NGC 104 LW 18,LP?,6.085561,-72.080463,0.019479,1819.056403,953.245682,1809.045881,933.372029
10,CXOGlb J002405.1-720435,X,6.021242,-72.076447,0.005008,1754.429257,2405.873141,1744.412102,2385.999194
11,CXOGlb J002412.1-720455,X,6.050588,-72.081950,0.008709,2044.783294,1702.057957,2034.769353,1682.185335
12,CXOGlb J002408.3-720433,X,6.034600,-72.076072,0.006566,1681.721235,2117.679692,1671.705396,2097.805413
13,[MSS2012] 31,*,6.027039,-72.092836,0.011483,2900.039902,2095.434720,2890.024164,2075.566005
14,CXOGlb J002405.9-720510,X,6.024733,-72.086325,0.004936,2444.929327,2218.796467,2434.913026,2198.925673

In [80]:
# only keep stars
catalog = catalog[catalog['OTYPE'].str.contains('\*')]

In [81]:
catalog.shape

(576, 9)

In [82]:
catalog.to_csv('variablesearch/coord_catalog.csv')